#!/usr/bin/env bash

{ # this ensures the entire script is downloaded #

shopt -s extglob
set -o errtrace
set -o errexit
set -o pipefail


log()  { printf "%b\n" "$*"; }
debug(){ [[ ${rvm_debug_flag:-0} -eq 0 ]] || printf "%b\n" "$*" >&2; }
warn() { log "WARN: $*" >&2 ; }
fail() { fail_with_code 1 "$*" ; }
fail_with_code() { code="$1" ; shift ; log "\nERROR: $*\n" >&2 ; exit "$code" ; }

# Check and Install all dependencies

function require_util() {
    type "$1" > /dev/null 2>&1 || command -v "$1" > /dev/null 2>&1 ||
        oops "you do not have '$1' installed, which I need to $2"
}

require_util git "install git"

mkdir -p ~/projects/sw/repos/personal && cd "$_"
if ! [[ -d "${HOME}/projects/sw/repos/personal/dotfiles" ]];
then 
    git clone https://github.com/ageekymonk/dotfiles.git
fi

cd dotfiles
make setup-common setup-mac

} # this ensures the entire script is downloaded #
