# Path to your oh-my-zsh installation.
if [[ "$(uname)" == "Darwin" ]]
then
    USERNAME=`whoami`
    export ZSH=/Users/$USERNAME/.oh-my-zsh
    # Would you like to use another custom folder than $ZSH/custom?
    ZSH_CUSTOM=/Users/$USERNAME/projects/sw/common/configs/zsh
    source /Users/$USERNAME/.iterm2_shell_integration.zsh

elif [[ "$(uname)" == "Linux" ]]
then
    USERNAME=`whoami`
    export ZSH=/home/$USERNAME/.oh-my-zsh
    # Would you like to use another custom folder than $ZSH/custom?
    ZSH_CUSTOM=/Users/$USERNAME/projects/sw/common/configs/zsh
    export SHELL=/bin/zsh
fi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
DEFAULT_USER=ramz.sivagurunathan

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=15

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"


# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git rvm docker zsh-autosuggestions zsh-syntax-highlighting history-substring-search)

# User configuration

# export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

source $ZSH_CUSTOM/zshalias

export EDITOR="emacsclient -nw"

if [[ "$(uname)" == "Darwin" ]]
then
    # Enable autojump
    [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

elif [[ "$(uname)" == "Linux" ]]
then
    . /usr/share/autojump/autojump.sh
    unset rvm_path
    source /home/$USERNAME/.rvm/scripts/rvm
fi

# Do not record duplicate in your history
export HISTCONTROL=ignoreboth:erasedups

# Set the path
export PATH=$PATH:${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin

# Set golang path and add to path
export GOPATH="$HOME/projects/sw/opensource/gospace"
export PATH="$PATH:$GOPATH/bin"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:/usr/local/opt/llvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

eval "$(direnv hook zsh)"

#export LIQUIBASE_HOME=$(find /usr/local/homebrew/Cellar/liquibase -name libexec)
# export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)

# Configure virtualenv and pyenv
if which pyenv > /dev/null;
then
    eval "$(pyenv init -)";
fi

if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)";
fi

source ~/.tmuxinator/bin/tmuxinator.zsh
export PATH="/usr/local/bin/Sencha/Cmd:$PATH"
export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

eval "$(fasd --init auto)"

_fzf_compgen_path() {
  ag -g "" "$1"
}
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/sbin:$PATH"
